import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://v2d.ceyinfo.com/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mimithaprabodani@gmail.com');
  await page.getByRole('textbox', { name: '********' }).click();
  await page.getByRole('textbox', { name: '********' }).press('CapsLock');
  await page.getByRole('textbox', { name: '********' }).fill('M');
  await page.getByRole('textbox', { name: '********' }).press('CapsLock');
  await page.getByRole('textbox', { name: '********' }).fill('');
  await page.getByRole('textbox', { name: '********' }).press('CapsLock');
  await page.getByRole('textbox', { name: '********' }).fill('M');
  await page.getByRole('textbox', { name: '********' }).press('CapsLock');
  await page.getByRole('textbox', { name: '********' }).fill('Mi@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('div:nth-child(8) > .inline-flex').click();
  await page.getByRole('button', { name: 'Manage Property' }).first().click();
  await page.getByText('Manage →Front').click();
  await page.getByRole('button', { name: 'Extras' }).click();
  await page.getByRole('button', { name: 'Travel Agencies' }).click();
  await page.getByRole('button', { name: 'Add Agency' }).click();
  await page.getByRole('textbox', { name: 'Agency Name *' }).click();
  await page.getByRole('textbox', { name: 'Agency Name *' }).fill('skyblueway');
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).fill('0765642354');
  await page.getByRole('textbox', { name: 'Full Name' }).click();
  await page.getByRole('textbox', { name: 'Full Name' }).fill('chamara');
  await page.getByRole('textbox', { name: 'Email (must be from gmail.com' }).click();
  await page.getByRole('textbox', { name: 'Email (must be from gmail.com' }).fill('chamara@gmail.com');
  await page.locator('.flex.flex-wrap.gap-2').click();
  await page.getByRole('textbox', { name: 'Type email and press Enter...' }).fill('skyblueway@yahoo.com');
  await page.getByRole('textbox', { name: 'VAT Number' }).click();
  await page.getByRole('textbox', { name: 'VAT Number' }).fill('176');
  await page.getByRole('switch', { name: 'Is VAT Applicable' }).click();
  await page.getByRole('combobox', { name: 'Currency Code' }).click();
  await page.getByRole('option', { name: 'LKR' }).press('Enter');
  await page.getByRole('radio', { name: 'Active', exact: true }).click();
  await page.getByRole('button', { name: 'Add Travel Agencies' }).click();
});