import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    
    test.setTimeout(120000);
    await page.goto('https://v2d.ceyinfo.com/', { waitUntil: 'networkidle' });
    await page.getByRole('link', { name: 'Login' }).click();
    await page.getByRole('textbox', { name: 'Email' }).click();
    await page.getByRole('textbox', { name: 'Email' }).fill('slakmaligunasingha@gmail.com');
    await page.getByRole('textbox', { name: '********' }).click();
    await page.getByRole('textbox', { name: '********' }).fill('123456');
    await page.getByRole('button', { name: 'Login' }).click();
    await page.getByRole('button', { name: 'Login' }).nth(1).click();
    await page.getByRole('button', { name: 'Manage Property' }).first().click();
    await page.getByRole('heading', { name: 'Front Desk' }).click();
    await page.getByRole('button', { name: 'Inquiries' }).click();
    await page.getByRole('button', { name: 'Close Sidebar' }).click();
    await page.getByRole('button', { name: '+ New Reservation' }).click();
    await page.getByRole('button', { name: '🧙 Step-by-Step Wizard Guided' }).dblclick();
    // await page.waitForTimeout(4000);
    // await page.getByLabel('May').getByRole('gridcell', { name: '12' }).click();
    // await page.getByLabel('May').getByRole('gridcell', { name: '14' }).click();
    await page.getByRole('button', { name: 'Flexible' }).click();
    await page.getByRole('button', { name: 'Custom' }).click();
    await page.getByRole('option', { name: 'agoda' }).click();
    await page.getByRole('textbox', { name: 'Voucher No' }).click();
    await page.getByRole('textbox', { name: 'Voucher No' }).fill('123');
    await page.getByRole('textbox', { name: 'Tour No' }).click();
    await page.getByRole('textbox', { name: 'Tour No' }).fill('456');
    await page.getByRole('button', { name: 'Room Selection' }).click();
    await page.locator('.inline-flex.items-center.justify-center.gap-2.whitespace-nowrap.rounded-md.text-sm.font-medium.transition-colors.focus-visible\\:outline-none.focus-visible\\:ring-1.focus-visible\\:ring-ring.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\]\\:size-4.\\[\\&_svg\\]\\:shrink-0.border').click();
    await page.getByRole('row', { name: 'Triple Price Missing 1 LKR 0.' }).locator('input[type="text"]').dblclick();
    await page.getByRole('row', { name: 'Triple Price Missing 1 LKR 0.' }).locator('input[type="text"]').fill('LKR 3,0000.00');
    await page.locator('.inline-flex.items-center.justify-center.gap-2.whitespace-nowrap.font-medium.transition-colors.focus-visible\\:outline-none.focus-visible\\:ring-1.focus-visible\\:ring-ring.disabled\\:pointer-events-none.disabled\\:opacity-50.\\[\\&_svg\\]\\:pointer-events-none.\\[\\&_svg\\]\\:size-4.\\[\\&_svg\\]\\:shrink-0.border.bg-background.shadow-sm.hover\\:text-accent-foreground.rounded-md.h-6.text-\\[10px\\]').click();
    await page.getByRole('combobox').click();
    await page.getByText('Special', { exact: true }).click();
    await page.getByRole('checkbox').click();
    await page.getByRole('button', { name: 'Authorize Entry' }).click();
    await page.getByRole('button', { name: 'Guest Info' }).click();
    await page.getByRole('button', { name: '+ Add Guest', exact: true }).click();
    await page.getByRole('button', { name: 'Search Guest' }).click();
    // await page.getByRole('row', { name: '#404 T thilanka — thilabnka@' }).getByRole('button').click();
    await page.getByRole('button', { name: 'Save Guest' }).click();
    await page.getByRole('combobox').filter({ hasText: 'None' }).click();
    await page.getByLabel('None').getByText('None').click();
    await page.getByRole('textbox', { name: 'Visit Purpose' }).click();
    await page.getByRole('textbox', { name: 'Visit Purpose' }).fill('Booking');
    await page.getByRole('textbox', { name: 'Notes' }).click();
    await page.getByRole('textbox', { name: 'Notes' }).fill('Booking');
    // await page.waitForTimeout(1000);
    await page.getByRole('button', { name: 'Summary' }).click();
    // await page.waitForTimeout(1000);
    await page.getByRole('button', { name: 'Save Reservation' }).click();
    await page.waitForTimeout(3000);

});