import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://v2d.ceyinfo.com/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('amnaf3479@gmail.com');
  await page.getByRole('textbox', { name: '********' }).click();
  await page.getByRole('textbox', { name: '********' }).fill('789456');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Login' }).nth(1).click();
  await page.getByRole('button', { name: 'Manage Property' }).first().click();
  await page.getByRole('heading', { name: 'Configuration' }).click();
  await page.getByRole('button', { name: 'F&B Operations' }).click();
  await page.getByRole('link', { name: 'Menu Items' }).click();
  await page.getByRole('button', { name: 'Add Menu Item' }).click();
  await page.getByRole('textbox', { name: 'Menu Name *' }).fill('test menu');
  await page.getByRole('combobox').first().click();
  await page.getByLabel('Amna Special Menu').getByText('Amna Special Menu').click();
  await page.getByRole('textbox', { name: 'Menu Code' }).click();
  await page.getByRole('textbox', { name: 'Menu Code' }).fill('amn');
  await page.getByRole('spinbutton', { name: 'Price' }).click();
  await page.getByRole('spinbutton', { name: 'Price' }).fill('01500');
  await page.getByRole('spinbutton', { name: 'Price' }).press('ArrowLeft');
  await page.getByRole('spinbutton', { name: 'Price' }).press('ArrowLeft');
  await page.getByRole('spinbutton', { name: 'Price' }).press('ArrowLeft');
  await page.getByRole('spinbutton', { name: 'Price' }).press('ArrowLeft');
  await page.getByRole('spinbutton', { name: 'Price' }).fill('1500');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('test meanu');
  await page.getByRole('button', { name: 'Add Menu Items' }).click();
});