// import { test, expect } from '@playwright/test';

// test('test', async ({ page }) => {
//   await page.goto('https://v2d.ceyinfo.com/');
//   await page.getByRole('link', { name: 'Login' }).click();
//   await page.getByRole('textbox', { name: 'Email' }).click();
//   await page.getByRole('textbox', { name: 'Email' }).fill('mimithaprabodani@gmail.com');
//   await page.getByRole('textbox', { name: '********' }).click();
//   await page.getByRole('textbox', { name: '********' }).fill('Mi@123');
//   await page.getByRole('button', { name: 'Login' }).click();
//   await page.locator('div:nth-child(8) > .inline-flex').click();
//   await page.getByRole('button', { name: 'Manage Property' }).first().click();
//   await page.getByRole('heading', { name: 'Human Resources' }).click();
//   await page.getByRole('link', { name: 'Employees' }).click();
//   await page.getByRole('button', { name: 'Add New' }).click();
//   await page.getByRole('textbox', { name: 'Enter first name' }).click();
//   await page.getByRole('textbox', { name: 'Enter first name' }).fill('amna');
//   await page.getByRole('textbox', { name: 'Enter last name' }).click();
//   await page.getByRole('textbox', { name: 'Enter last name' }).fill('suhaib');
//   await page.getByRole('textbox', { name: 'Enter NIC' }).click();
//   await page.getByRole('textbox', { name: 'Enter NIC' }).fill('2001456747');
//   await page.getByRole('combobox', { name: 'Designation *' }).click();
//   await page.getByLabel('Receptionist').getByText('Receptionist').click();
//   await page.getByRole('combobox', { name: 'Department *' }).click();
//   await page.getByLabel('Engineering / Maintenance').getByText('Engineering / Maintenance').click();
//   await page.getByRole('combobox', { name: 'Status *' }).click();
//   await page.getByLabel('Active').getByText('Active').click();
//   await page.getByPlaceholder('Enter salary').click();
//   await page.getByPlaceholder('Enter salary').fill('65000');
//   await page.getByRole('textbox', { name: 'Enter email' }).click();
//   await page.getByRole('textbox', { name: 'Enter email' }).fill('malee@gmail.com');
//   await page.getByRole('textbox', { name: 'Enter mobile' }).click();
//   await page.getByRole('textbox', { name: 'Enter mobile' }).fill('0745896123');
//   await page.getByRole('textbox', { name: 'Enter address' }).click();
//   await page.getByRole('textbox', { name: 'Enter address' }).fill('peradeniya');
//   await page.getByRole('combobox', { name: 'Province *' }).click();
//   await page.getByLabel('Central Province', { exact: true }).getByText('Central Province').click();
//   await page.getByRole('combobox', { name: 'City *' }).click();
//   await page.getByLabel('Kandy').getByText('Kandy').click();
//   await page.getByRole('button', { name: 'Save Employee' }).click();

// });
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://v2d.ceyinfo.com/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('mimithaprabodani@gmail.com');
  await page.getByRole('textbox', { name: '********' }).click();
  await page.getByRole('textbox', { name: '********' }).fill('Mi@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('div:nth-child(8) > .inline-flex').click();
  await page.getByRole('button', { name: 'Manage Property' }).first().click();
  await page.locator('div:nth-child(4) > .p-6 > .flex.flex-col > .flex.items-start').click();
  await page.getByRole('link', { name: 'Employees' }).click();
  await page.getByRole('button', { name: 'Add New' }).click();
  await page.getByRole('textbox', { name: 'Enter first name' }).click();
  await page.getByRole('textbox', { name: 'Enter first name' }).fill('dehemi');
  await page.getByRole('textbox', { name: 'Enter last name' }).click();
  await page.getByRole('textbox', { name: 'Enter last name' }).fill('upeksha');
  await page.getByRole('textbox', { name: 'Enter NIC' }).click();
  await page.getByRole('textbox', { name: 'Enter NIC' }).fill('20016972453');
  await page.getByRole('combobox', { name: 'Designation *' }).click();
  await page.getByLabel('Receptionist').getByText('Receptionist').click();
  await page.getByRole('combobox', { name: 'Department *' }).click();
  await page.getByLabel('Front Office').getByText('Front Office').click();
  await page.getByRole('combobox', { name: 'Status *' }).click();
  await page.getByLabel('Active').getByText('Active').click();
  await page.getByPlaceholder('Enter salary').click();
  await page.getByPlaceholder('Enter salary').fill('75000');
  await page.getByRole('textbox', { name: 'Enter email' }).click();
  await page.getByRole('textbox', { name: 'Enter email' }).fill('dehemiupeksha@gmail.com');
  await page.getByRole('textbox', { name: 'Enter mobile' }).click();
  await page.getByRole('textbox', { name: 'Enter mobile' }).fill('0751246782');
  await page.getByRole('textbox', { name: 'Enter address' }).click();
  await page.getByRole('textbox', { name: 'Enter address' }).fill('galgamuwa,kurunegala');
  await page.getByRole('combobox', { name: 'Province *' }).click();
  await page.getByLabel('Central Province', { exact: true }).getByText('Central Province').click();
  await page.getByRole('combobox', { name: 'City *' }).click();
  await page.getByLabel('Kandy').getByText('Kandy').click();
  await page.getByRole('button', { name: 'Save Employee' }).click();
});