import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    
    test.setTimeout(300000);
    await page.goto('https://v2d.ceyinfo.com/', { waitUntil: 'networkidle' });
    await page.getByRole('link', { name: 'Login' }).click();
    await page.getByRole('textbox', { name: 'Email' }).click();
    await page.getByRole('textbox', { name: 'Email' }).fill('slakmaligunasingha@gmail.com');
    await page.getByRole('textbox', { name: '********' }).click();
    await page.getByRole('textbox', { name: '********' }).fill('123456');
    await page.getByRole('button', { name: 'Login' }).click();
    await page.locator('div:nth-child(9) > .inline-flex').click();
    await page.getByRole('button', { name: 'Manage Property' }).click();
    await page.getByRole('heading', { name: 'Configuration' }).click();
    await page.getByRole('link', { name: 'Building/Rooms' }).click();
    await page.getByRole('button', { name: 'Close Sidebar' }).click();
    await page.getByText('Cnex1 floors').click();
    await page.getByText('Ground FloorOrientation: NORTHLevel: 0Rooms:').click();
    await page.getByRole('button', { name: 'Add Unit', exact: true }).click();
    
    // ----- Add room -----
    
    await page.getByPlaceholder('e.g., 35.5').press('ArrowLeft');
    await page.getByPlaceholder('e.g., 35.5').fill('201');
    await page.getByRole('button', { name: 'Save' }).click();
    await page.getByRole('button').nth(4).click();
    const page1Promise = page.waitForEvent('popup');
    await page.getByRole('link', { name: 'Front Desk' }).click();
    const page1 = await page1Promise;
    await page1.getByRole('button', { name: 'House Keeping' }).click();
    await page1.getByRole('button', { name: 'Close Sidebar' }).click();
    await page1.getByRole('button', { name: 'Open Sidebar' }).click();
    await page1.getByRole('button', { name: 'Inquiries' }).click();
    await page1.getByRole('button', { name: 'Close Sidebar' }).click();
    await page1.getByRole('button', { name: '+ New Reservation' }).click();
    await page1.getByRole('button', { name: '📋 Full Form All fields' }).click();
    await page1.getByLabel('May').getByRole('gridcell', { name: '8', exact: true }).click();
    await page1.getByLabel('May').getByRole('gridcell', { name: '10' }).click();
    await page1.getByRole('button', { name: 'Custom' }).click();
    await page1.getByLabel('fit(local)').getByText('fit(local)').click();
    await page1.locator('tr:nth-child(2) > td:nth-child(8) > .flex > .inline-flex.items-center.justify-center.gap-2.whitespace-nowrap.rounded-md.text-sm').click();
    await page1.getByRole('combobox').filter({ hasText: 'Select Room' }).click();
    await page1.getByLabel('600').getByText('600').click();
    await page1.getByRole('cell', { name: 'Room No Adults Children Meal' }).getByRole('textbox').click();
    await page1.getByRole('cell', { name: 'Room No Adults Children Meal' }).getByRole('textbox').dblclick();
    await page1.getByRole('cell', { name: 'Room No Adults Children Meal' }).getByRole('textbox').fill('LKR 3,0000.00');
    await page1.getByRole('button', { name: 'Add Guest Info' }).click();
    await page1.getByRole('button', { name: 'Search Guest' }).click();
    await page1.getByRole('row', { name: '#9 HR Hotel Reservations —' }).getByRole('button').click();
    await page1.getByRole('button', { name: 'Save Guest' }).click();
    await page1.getByRole('combobox').filter({ hasText: 'None' }).click();
    await page1.getByLabel('Confirmed').getByText('Confirmed').click();
    await page1.getByRole('button', { name: 'Create Reservation' }).click();
    await page1.getByRole('button', { name: 'Room Allocation' }).click();
    await page1.getByText('#14·Twin StandardArriving').click();
    await page1.getByRole('button', { name: 'House Keeping' }).click();
    await page1.getByRole('button', { name: 'Open Sidebar' }).click();
    await page1.getByRole('button', { name: 'Check-Ins' }).click();
    await page1.getByRole('button', { name: 'Close Sidebar' }).click();
    await page1.getByRole('button', { name: 'GRC' }).click();
    await page1.locator('div').filter({ hasText: /^Click to upload \(2 remaining\)$/ }).first().click();
    await page1.locator('body').setInputFiles('download (1).jpeg');
    await page1.getByRole('button', { name: 'Save Registration' }).click();
    await page1.getByRole('button', { name: 'Save Check-In Time' }).click();
    await page1.getByRole('button', { name: 'Checkouts' }).click();
    await page1.getByRole('tab', { name: 'All Check-outs' }).click();
    await page1.getByRole('button', { name: 'Check Out' }).first().click();
    const page2Promise = page1.waitForEvent('popup');
    await page1.getByRole('button', { name: 'Create Folio' }).click();
    const page2 = await page2Promise;
    await page2.getByRole('button', { name: 'Save All' }).click();
    await page2.getByRole('button', { name: 'Invoice' }).click();
    await page2.getByRole('button', { name: 'Save Invoice' }).click();
    await page2.getByRole('button', { name: 'Record Payment' }).click();
    await page2.getByRole('combobox').filter({ hasText: 'Select a payment method' }).click();
    await page2.getByLabel('Cash').getByText('Cash').click();
    await page2.getByRole('textbox', { name: '0.00' }).click();
    await page2.getByRole('textbox', { name: '0.00' }).fill('60000');
    await page2.getByRole('button', { name: 'Pay', exact: true }).click();
    await page2.getByRole('button').nth(3).click();
    const page3Promise = page2.waitForEvent('popup');
    await page2.getByRole('link', { name: 'Front Desk' }).click();
    const page3 = await page3Promise;
    await page3.getByRole('button', { name: 'Open Sidebar' }).click();
    await page3.getByRole('button', { name: 'Checkouts' }).click();
    await page3.getByRole('button', { name: 'Close Sidebar' }).click();
    await page3.getByRole('tab', { name: 'All Check-outs' }).click();
    await page3.getByRole('button', { name: 'Check Out' }).first().click();
    await page3.getByRole('button', { name: 'Save Check-out Time' }).click();
    await page3.locator('div').filter({ hasText: '×Guest Check-OutReservation' }).nth(5).click();
    await page3.getByRole('button', { name: '×' }).click();
    await page3.getByRole('button', { name: 'House Keeping' }).click();

});