import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://v2d.ceyinfo.com/');
  await page.getByRole('link', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('dehemiupeksha6@gmail.com');
  await page.getByRole('textbox', { name: '********' }).click();
  await page.getByRole('textbox', { name: '********' }).fill('12345');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Login' }).nth(5).click();
  await page.getByRole('button', { name: 'Manage Property' }).nth(1).click();
  await page.getByRole('button', { name: 'Front Desk Reservations,' }).click();
  await page.getByRole('button', { name: 'New' }).click();
  await page.getByRole('button', { name: '📋 Full Form All fields' }).click();
  await page.getByLabel('June').getByRole('gridcell', { name: '25' }).click();
  await page.getByLabel('June').getByRole('gridcell', { name: '27' }).click();
  await page.getByRole('button', { name: 'Sri Lanka Season -' }).click();
  await page.locator('.flex.h-5.w-5.items-center.justify-center.border-l').first().click();
  await page.getByRole('button', { name: 'Add Guest Info' }).click();
  await page.getByRole('button', { name: 'Search Guest' }).click();
  await page.getByRole('row', { name: '#30 IS Isuru Sajith' }).getByRole('button').click();
  await page.getByRole('button', { name: 'Save Guest' }).click();
  await page.getByRole('combobox').filter({ hasText: 'None' }).click();
  await page.getByLabel('Confirmed').getByText('Confirmed').click();
  await page.getByRole('button', { name: 'Create Reservation' }).click();
  await page.getByRole('combobox').filter({ hasText: 'Select' }).click();
  await page.getByLabel('booking.com').getByText('booking.com').click();
  await page.getByRole('button', { name: 'Create Reservation' }).click();
  await page.getByRole('button', { name: 'View' }).nth(2).click();
  await page.getByRole('button', { name: 'Stay Dates *' }).click();
  await page.getByLabel('June').getByRole('gridcell', { name: '28' }).click();
  await page.getByLabel('June').getByRole('gridcell', { name: '30' }).click();
  await page.getByRole('button', { name: 'Update Reservation' }).click();
  await page.getByRole('button', { name: 'View' }).nth(4).click();
  await page.locator('.flex.h-5.w-5.items-center.justify-center.border-l').first().click();
  await page.getByRole('button', { name: 'Update Reservation' }).click();
  await page.getByRole('button', { name: 'View' }).nth(5).click();
  await page.getByRole('row', { name: 'Single 1 LKR 16,500.00 LKR 33' }).getByRole('combobox').click();
  await page.getByLabel('RO').getByText('RO', { exact: true }).click();
  await page.getByRole('button', { name: 'Update Reservation' }).click();
});